const list = [
    {
      id: 1,
      title: "BANANA",
      author: "AFRICA",
      price: 98,
      img: "https://tse2.mm.bing.net/th?id=OIP.XFvgjrUne5hvG2AZFEjjzgHaEK&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 2,
      title: "GRAPES",
      author: "AMERICA",
      price: 143,
      img: "https://tse1.mm.bing.net/th?id=OIP.XTVcz5kANztvSEqO9D0ZUwHaEo&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 3,
      title: "MANGO",
      author: "UNITED KONGDOM",
      price: 57,
      img: "https://tse4.mm.bing.net/th?id=OIP.qi28enNUWaZuC0TwIfvF5wHaEo&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 4,
      title: "CUSTARD APPLE",
      author: "PAKISTHAN",
      price: 149,
      img: "https://tse3.mm.bing.net/th?id=OIP.lAIBuTdaqO77DQ6hw3he0gHaE7&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 5,
      title: "POMEGRANATE",
      author: "GERMANY",
      price: 135,
      img: "https://tse1.mm.bing.net/th?id=OIP.IKB7G_jY59lK-4_VmUsDRQHaFF&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 6,
      title: "SAPOTA",
      author: "AUSTRALIA",
      price: 693,
      img: "https://tse4.mm.bing.net/th?id=OIP.QmtFQWt_PPtKT0tfTDbVlwHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 7,
      title: "STRAWBERRY",
      author: "FRANCE",
      price: 289,
      img: "https://tse3.mm.bing.net/th?id=OIP.OmSz410prsUB_-kVibYV4AHaE8&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 8,
      title: "PEACH",
      author: "NEW ZEALAND",
      price: 80,
      img: "https://tse2.mm.bing.net/th?id=OIP.kM7RKrXyONtgu2wLmpFszwHaFV&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 9,
      title: "GREAN APPLE",
      author: "SOUTH AFRICA",
      price: 86,
      img: "https://tse3.mm.bing.net/th?id=OIP.n_CQTHRbeNZD_bP_zVa0NwHaH3&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 10,
      title: "GUAVA",
      author: "SRI LANKA",
      price: 120,
      img: "https://tse1.mm.bing.net/th?id=OIP.v0q5YnDJPmK0npQyaQjwZgHaEK&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 11,
      title: "JACK FRUIT",
      author: "IRELAND",
      price: 157,
      img: "https://tse4.mm.bing.net/th?id=OIP.Ky8qeMg4nNCbaVKdx-tAfwHaFj&pid=Api&P=0&h=180",
      amount: 1,
    }
  ];
  export default list;
